# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consumer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consumer.proto',
  package='',
  syntax='proto3',
  serialized_pb=b'\n\x0e\x63onsumer.proto\"_\n\x15\x43onsumerCreateRequest\x12\x0f\n\x07numbers\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\x04\x12#\n\x08material\x18\x03 \x01(\x0b\x32\x11.ConsumerMaterial\"\x18\n\x16\x43onsumerCreateResponse\"<\n\x17\x43onsumerRetrieveRequest\x12\x0f\n\x07numbers\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\x04\"?\n\x18\x43onsumerRetrieveResponse\x12#\n\x08material\x18\x01 \x01(\x0b\x32\x11.ConsumerMaterial\"D\n\x1c\x43onsumerBatchRetrieveRequest\x12\x10\n\x08numberss\x18\x01 \x03(\t\x12\x12\n\nidentities\x18\x02 \x03(\x04\"E\n\x1d\x43onsumerBatchRetrieveResponse\x12$\n\tmaterials\x18\x01 \x03(\x0b\x32\x11.ConsumerMaterial\"_\n\x15\x43onsumerUpdateRequest\x12\x0f\n\x07numbers\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\x04\x12#\n\x08material\x18\x03 \x01(\x0b\x32\x11.ConsumerMaterial\"\x18\n\x16\x43onsumerUpdateResponse\":\n\x15\x43onsumerDeleteRequest\x12\x0f\n\x07numbers\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\x04\"\x18\n\x16\x43onsumerDeleteResponse\"\xb5\x01\n\x10\x43onsumerMaterial\x12\x0f\n\x07numbers\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t\x12\x0c\n\x04sexy\x18\x04 \x01(\t\x12\x0b\n\x03\x61ge\x18\x05 \x01(\r\x12\r\n\x05\x65mail\x18\x06 \x01(\t\x12\x11\n\tintroduce\x18\x07 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\x12\x10\n\x08location\x18\t \x01(\t\x12\x0e\n\x06qrcode\x18\n \x01(\tb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONSUMERCREATEREQUEST = _descriptor.Descriptor(
  name='ConsumerCreateRequest',
  full_name='ConsumerCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='ConsumerCreateRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='ConsumerCreateRequest.identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='ConsumerCreateRequest.material', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=113,
)


_CONSUMERCREATERESPONSE = _descriptor.Descriptor(
  name='ConsumerCreateResponse',
  full_name='ConsumerCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=139,
)


_CONSUMERRETRIEVEREQUEST = _descriptor.Descriptor(
  name='ConsumerRetrieveRequest',
  full_name='ConsumerRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='ConsumerRetrieveRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='ConsumerRetrieveRequest.identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=201,
)


_CONSUMERRETRIEVERESPONSE = _descriptor.Descriptor(
  name='ConsumerRetrieveResponse',
  full_name='ConsumerRetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='material', full_name='ConsumerRetrieveResponse.material', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=266,
)


_CONSUMERBATCHRETRIEVEREQUEST = _descriptor.Descriptor(
  name='ConsumerBatchRetrieveRequest',
  full_name='ConsumerBatchRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numberss', full_name='ConsumerBatchRetrieveRequest.numberss', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identities', full_name='ConsumerBatchRetrieveRequest.identities', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=336,
)


_CONSUMERBATCHRETRIEVERESPONSE = _descriptor.Descriptor(
  name='ConsumerBatchRetrieveResponse',
  full_name='ConsumerBatchRetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='materials', full_name='ConsumerBatchRetrieveResponse.materials', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=407,
)


_CONSUMERUPDATEREQUEST = _descriptor.Descriptor(
  name='ConsumerUpdateRequest',
  full_name='ConsumerUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='ConsumerUpdateRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='ConsumerUpdateRequest.identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='ConsumerUpdateRequest.material', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=504,
)


_CONSUMERUPDATERESPONSE = _descriptor.Descriptor(
  name='ConsumerUpdateResponse',
  full_name='ConsumerUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=530,
)


_CONSUMERDELETEREQUEST = _descriptor.Descriptor(
  name='ConsumerDeleteRequest',
  full_name='ConsumerDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='ConsumerDeleteRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='ConsumerDeleteRequest.identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=590,
)


_CONSUMERDELETERESPONSE = _descriptor.Descriptor(
  name='ConsumerDeleteResponse',
  full_name='ConsumerDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=616,
)


_CONSUMERMATERIAL = _descriptor.Descriptor(
  name='ConsumerMaterial',
  full_name='ConsumerMaterial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='ConsumerMaterial.numbers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='ConsumerMaterial.nickname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar', full_name='ConsumerMaterial.avatar', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sexy', full_name='ConsumerMaterial.sexy', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='age', full_name='ConsumerMaterial.age', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='ConsumerMaterial.email', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='introduce', full_name='ConsumerMaterial.introduce', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='ConsumerMaterial.country', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='ConsumerMaterial.location', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qrcode', full_name='ConsumerMaterial.qrcode', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=800,
)

_CONSUMERCREATEREQUEST.fields_by_name['material'].message_type = _CONSUMERMATERIAL
_CONSUMERRETRIEVERESPONSE.fields_by_name['material'].message_type = _CONSUMERMATERIAL
_CONSUMERBATCHRETRIEVERESPONSE.fields_by_name['materials'].message_type = _CONSUMERMATERIAL
_CONSUMERUPDATEREQUEST.fields_by_name['material'].message_type = _CONSUMERMATERIAL
DESCRIPTOR.message_types_by_name['ConsumerCreateRequest'] = _CONSUMERCREATEREQUEST
DESCRIPTOR.message_types_by_name['ConsumerCreateResponse'] = _CONSUMERCREATERESPONSE
DESCRIPTOR.message_types_by_name['ConsumerRetrieveRequest'] = _CONSUMERRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['ConsumerRetrieveResponse'] = _CONSUMERRETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['ConsumerBatchRetrieveRequest'] = _CONSUMERBATCHRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['ConsumerBatchRetrieveResponse'] = _CONSUMERBATCHRETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['ConsumerUpdateRequest'] = _CONSUMERUPDATEREQUEST
DESCRIPTOR.message_types_by_name['ConsumerUpdateResponse'] = _CONSUMERUPDATERESPONSE
DESCRIPTOR.message_types_by_name['ConsumerDeleteRequest'] = _CONSUMERDELETEREQUEST
DESCRIPTOR.message_types_by_name['ConsumerDeleteResponse'] = _CONSUMERDELETERESPONSE
DESCRIPTOR.message_types_by_name['ConsumerMaterial'] = _CONSUMERMATERIAL

ConsumerCreateRequest = _reflection.GeneratedProtocolMessageType('ConsumerCreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERCREATEREQUEST,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerCreateRequest)
  ))
_sym_db.RegisterMessage(ConsumerCreateRequest)

ConsumerCreateResponse = _reflection.GeneratedProtocolMessageType('ConsumerCreateResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERCREATERESPONSE,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerCreateResponse)
  ))
_sym_db.RegisterMessage(ConsumerCreateResponse)

ConsumerRetrieveRequest = _reflection.GeneratedProtocolMessageType('ConsumerRetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERRETRIEVEREQUEST,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerRetrieveRequest)
  ))
_sym_db.RegisterMessage(ConsumerRetrieveRequest)

ConsumerRetrieveResponse = _reflection.GeneratedProtocolMessageType('ConsumerRetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERRETRIEVERESPONSE,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerRetrieveResponse)
  ))
_sym_db.RegisterMessage(ConsumerRetrieveResponse)

ConsumerBatchRetrieveRequest = _reflection.GeneratedProtocolMessageType('ConsumerBatchRetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERBATCHRETRIEVEREQUEST,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerBatchRetrieveRequest)
  ))
_sym_db.RegisterMessage(ConsumerBatchRetrieveRequest)

ConsumerBatchRetrieveResponse = _reflection.GeneratedProtocolMessageType('ConsumerBatchRetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERBATCHRETRIEVERESPONSE,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerBatchRetrieveResponse)
  ))
_sym_db.RegisterMessage(ConsumerBatchRetrieveResponse)

ConsumerUpdateRequest = _reflection.GeneratedProtocolMessageType('ConsumerUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERUPDATEREQUEST,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerUpdateRequest)
  ))
_sym_db.RegisterMessage(ConsumerUpdateRequest)

ConsumerUpdateResponse = _reflection.GeneratedProtocolMessageType('ConsumerUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERUPDATERESPONSE,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerUpdateResponse)
  ))
_sym_db.RegisterMessage(ConsumerUpdateResponse)

ConsumerDeleteRequest = _reflection.GeneratedProtocolMessageType('ConsumerDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERDELETEREQUEST,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerDeleteRequest)
  ))
_sym_db.RegisterMessage(ConsumerDeleteRequest)

ConsumerDeleteResponse = _reflection.GeneratedProtocolMessageType('ConsumerDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERDELETERESPONSE,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerDeleteResponse)
  ))
_sym_db.RegisterMessage(ConsumerDeleteResponse)

ConsumerMaterial = _reflection.GeneratedProtocolMessageType('ConsumerMaterial', (_message.Message,), dict(
  DESCRIPTOR = _CONSUMERMATERIAL,
  __module__ = 'consumer_pb2'
  # @@protoc_insertion_point(class_scope:ConsumerMaterial)
  ))
_sym_db.RegisterMessage(ConsumerMaterial)


# @@protoc_insertion_point(module_scope)
