# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merchant.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='merchant.proto',
  package='',
  syntax='proto3',
  serialized_pb=b'\n\x0emerchant.proto\"\x97\x01\n\x15MerchantCreateRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x19\n\x11merchant_identity\x18\x02 \x01(\x04\x12#\n\x08material\x18\x03 \x01(\x0b\x32\x11.MerchantMaterial\x12.\n\x0ematerial_alter\x18\x04 \x01(\x0b\x32\x16.MerchantMaterialAlter\"\x18\n\x16MerchantCreateResponse\"D\n\x17MerchantRetrieveRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x19\n\x11merchant_identity\x18\x02 \x01(\x04\"?\n\x18MerchantRetrieveResponse\x12#\n\x08material\x18\x01 \x01(\x0b\x32\x11.MerchantMaterial\"P\n\x1cMerchantBatchRetrieveRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\t\x12\x1f\n\x17merchant_identity_multi\x18\x02 \x03(\x04\"E\n\x1dMerchantBatchRetrieveResponse\x12$\n\tmaterials\x18\x01 \x03(\x0b\x32\x11.MerchantMaterial\"g\n\x15MerchantUpdateRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x19\n\x11merchant_identity\x18\x02 \x01(\x04\x12#\n\x08material\x18\x03 \x01(\x0b\x32\x11.MerchantMaterial\"\x18\n\x16MerchantUpdateResponse\"B\n\x15MerchantDeleteRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x19\n\x11merchant_identity\x18\x02 \x01(\x04\"\x18\n\x16MerchantDeleteResponse\"S\n\x10MerchantMaterial\x12\x10\n\x08\x63ontract\x18\x01 \x01(\t\x12\x15\n\rmerchant_name\x18\x02 \x01(\t\x12\x16\n\x0emanager_number\x18\x03 \x01(\t\"\x9f\x01\n\x15MerchantMaterialAlter\x12\x0e\n\x06number\x18\x02 \x01(\t\x12\x0c\n\x04logo\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x11\n\tintroduce\x18\x05 \x01(\t\x12\x11\n\tlongitude\x18\x06 \x01(\x02\x12\x10\n\x08latitude\x18\x07 \x01(\x02\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\x12\x10\n\x08location\x18\t \x01(\tb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MERCHANTCREATEREQUEST = _descriptor.Descriptor(
  name='MerchantCreateRequest',
  full_name='MerchantCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantCreateRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity', full_name='MerchantCreateRequest.merchant_identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='MerchantCreateRequest.material', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material_alter', full_name='MerchantCreateRequest.material_alter', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=170,
)


_MERCHANTCREATERESPONSE = _descriptor.Descriptor(
  name='MerchantCreateResponse',
  full_name='MerchantCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=196,
)


_MERCHANTRETRIEVEREQUEST = _descriptor.Descriptor(
  name='MerchantRetrieveRequest',
  full_name='MerchantRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantRetrieveRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity', full_name='MerchantRetrieveRequest.merchant_identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=266,
)


_MERCHANTRETRIEVERESPONSE = _descriptor.Descriptor(
  name='MerchantRetrieveResponse',
  full_name='MerchantRetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='material', full_name='MerchantRetrieveResponse.material', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=331,
)


_MERCHANTBATCHRETRIEVEREQUEST = _descriptor.Descriptor(
  name='MerchantBatchRetrieveRequest',
  full_name='MerchantBatchRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='MerchantBatchRetrieveRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity_multi', full_name='MerchantBatchRetrieveRequest.merchant_identity_multi', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=413,
)


_MERCHANTBATCHRETRIEVERESPONSE = _descriptor.Descriptor(
  name='MerchantBatchRetrieveResponse',
  full_name='MerchantBatchRetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='materials', full_name='MerchantBatchRetrieveResponse.materials', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=484,
)


_MERCHANTUPDATEREQUEST = _descriptor.Descriptor(
  name='MerchantUpdateRequest',
  full_name='MerchantUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantUpdateRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity', full_name='MerchantUpdateRequest.merchant_identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='MerchantUpdateRequest.material', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=486,
  serialized_end=589,
)


_MERCHANTUPDATERESPONSE = _descriptor.Descriptor(
  name='MerchantUpdateResponse',
  full_name='MerchantUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=615,
)


_MERCHANTDELETEREQUEST = _descriptor.Descriptor(
  name='MerchantDeleteRequest',
  full_name='MerchantDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantDeleteRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity', full_name='MerchantDeleteRequest.merchant_identity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=683,
)


_MERCHANTDELETERESPONSE = _descriptor.Descriptor(
  name='MerchantDeleteResponse',
  full_name='MerchantDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=709,
)


_MERCHANTMATERIAL = _descriptor.Descriptor(
  name='MerchantMaterial',
  full_name='MerchantMaterial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='MerchantMaterial.contract', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_name', full_name='MerchantMaterial.merchant_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manager_number', full_name='MerchantMaterial.manager_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=711,
  serialized_end=794,
)


_MERCHANTMATERIALALTER = _descriptor.Descriptor(
  name='MerchantMaterialAlter',
  full_name='MerchantMaterialAlter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantMaterialAlter.number', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logo', full_name='MerchantMaterialAlter.logo', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='MerchantMaterialAlter.email', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='introduce', full_name='MerchantMaterialAlter.introduce', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='MerchantMaterialAlter.longitude', index=4,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='MerchantMaterialAlter.latitude', index=5,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='MerchantMaterialAlter.country', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='MerchantMaterialAlter.location', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=797,
  serialized_end=956,
)

_MERCHANTCREATEREQUEST.fields_by_name['material'].message_type = _MERCHANTMATERIAL
_MERCHANTCREATEREQUEST.fields_by_name['material_alter'].message_type = _MERCHANTMATERIALALTER
_MERCHANTRETRIEVERESPONSE.fields_by_name['material'].message_type = _MERCHANTMATERIAL
_MERCHANTBATCHRETRIEVERESPONSE.fields_by_name['materials'].message_type = _MERCHANTMATERIAL
_MERCHANTUPDATEREQUEST.fields_by_name['material'].message_type = _MERCHANTMATERIAL
DESCRIPTOR.message_types_by_name['MerchantCreateRequest'] = _MERCHANTCREATEREQUEST
DESCRIPTOR.message_types_by_name['MerchantCreateResponse'] = _MERCHANTCREATERESPONSE
DESCRIPTOR.message_types_by_name['MerchantRetrieveRequest'] = _MERCHANTRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['MerchantRetrieveResponse'] = _MERCHANTRETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['MerchantBatchRetrieveRequest'] = _MERCHANTBATCHRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['MerchantBatchRetrieveResponse'] = _MERCHANTBATCHRETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['MerchantUpdateRequest'] = _MERCHANTUPDATEREQUEST
DESCRIPTOR.message_types_by_name['MerchantUpdateResponse'] = _MERCHANTUPDATERESPONSE
DESCRIPTOR.message_types_by_name['MerchantDeleteRequest'] = _MERCHANTDELETEREQUEST
DESCRIPTOR.message_types_by_name['MerchantDeleteResponse'] = _MERCHANTDELETERESPONSE
DESCRIPTOR.message_types_by_name['MerchantMaterial'] = _MERCHANTMATERIAL
DESCRIPTOR.message_types_by_name['MerchantMaterialAlter'] = _MERCHANTMATERIALALTER

MerchantCreateRequest = _reflection.GeneratedProtocolMessageType('MerchantCreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTCREATEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantCreateRequest)
  ))
_sym_db.RegisterMessage(MerchantCreateRequest)

MerchantCreateResponse = _reflection.GeneratedProtocolMessageType('MerchantCreateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTCREATERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantCreateResponse)
  ))
_sym_db.RegisterMessage(MerchantCreateResponse)

MerchantRetrieveRequest = _reflection.GeneratedProtocolMessageType('MerchantRetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTRETRIEVEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantRetrieveRequest)
  ))
_sym_db.RegisterMessage(MerchantRetrieveRequest)

MerchantRetrieveResponse = _reflection.GeneratedProtocolMessageType('MerchantRetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTRETRIEVERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantRetrieveResponse)
  ))
_sym_db.RegisterMessage(MerchantRetrieveResponse)

MerchantBatchRetrieveRequest = _reflection.GeneratedProtocolMessageType('MerchantBatchRetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTBATCHRETRIEVEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantBatchRetrieveRequest)
  ))
_sym_db.RegisterMessage(MerchantBatchRetrieveRequest)

MerchantBatchRetrieveResponse = _reflection.GeneratedProtocolMessageType('MerchantBatchRetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTBATCHRETRIEVERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantBatchRetrieveResponse)
  ))
_sym_db.RegisterMessage(MerchantBatchRetrieveResponse)

MerchantUpdateRequest = _reflection.GeneratedProtocolMessageType('MerchantUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTUPDATEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantUpdateRequest)
  ))
_sym_db.RegisterMessage(MerchantUpdateRequest)

MerchantUpdateResponse = _reflection.GeneratedProtocolMessageType('MerchantUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTUPDATERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantUpdateResponse)
  ))
_sym_db.RegisterMessage(MerchantUpdateResponse)

MerchantDeleteRequest = _reflection.GeneratedProtocolMessageType('MerchantDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTDELETEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantDeleteRequest)
  ))
_sym_db.RegisterMessage(MerchantDeleteRequest)

MerchantDeleteResponse = _reflection.GeneratedProtocolMessageType('MerchantDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTDELETERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantDeleteResponse)
  ))
_sym_db.RegisterMessage(MerchantDeleteResponse)

MerchantMaterial = _reflection.GeneratedProtocolMessageType('MerchantMaterial', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTMATERIAL,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantMaterial)
  ))
_sym_db.RegisterMessage(MerchantMaterial)

MerchantMaterialAlter = _reflection.GeneratedProtocolMessageType('MerchantMaterialAlter', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTMATERIALALTER,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantMaterialAlter)
  ))
_sym_db.RegisterMessage(MerchantMaterialAlter)


# @@protoc_insertion_point(module_scope)
