# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: merchant.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='merchant.proto',
  package='',
  syntax='proto3',
  serialized_pb=b'\n\x0emerchant.proto\"_\n\x15MerchantCreateRequest\x12\x0f\n\x07numbers\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\t\x12#\n\x08material\x18\x03 \x01(\x0b\x32\x11.MerchantMaterial\"3\n\x16MerchantCreateResponse\x12\x19\n\x11material_identity\x18\x01 \x01(\t\"X\n\x17MerchantRetrieveRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x1b\n\x13merchant_identities\x18\x03 \x03(\t\"@\n\x18MerchantRetrieveResponse\x12$\n\tmaterials\x18\x01 \x03(\x0b\x32\x11.MerchantMaterial\"C\n\x1cMerchantBatchRetrieveRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\t\x12\x12\n\nidentities\x18\x02 \x03(\t\"E\n\x1dMerchantBatchRetrieveResponse\x12$\n\tmaterials\x18\x01 \x03(\x0b\x32\x11.MerchantMaterial\"y\n\x15MerchantUpdateRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x19\n\x11merchant_identity\x18\x03 \x01(\t\x12#\n\x08material\x18\x04 \x01(\x0b\x32\x11.MerchantMaterial\"\x18\n\x16MerchantUpdateResponse\"T\n\x15MerchantDeleteRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x10\n\x08identity\x18\x02 \x01(\t\x12\x19\n\x11merchant_identity\x18\x03 \x01(\t\"\x18\n\x16MerchantDeleteResponse\"\x87\x02\n\x10MerchantMaterial\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07name_en\x18\x02 \x01(\t\x12\x0f\n\x07numbers\x18\x03 \x01(\t\x12\x10\n\x08verified\x18\x04 \x01(\t\x12\x0e\n\x06qrcode\x18\x15 \x01(\t\x12\x17\n\x0f\x63ontact_numbers\x18\x16 \x01(\t\x12\x0c\n\x04logo\x18\x17 \x01(\t\x12\r\n\x05\x65mail\x18\x18 \x01(\t\x12\x11\n\tintroduce\x18\x19 \x01(\t\x12\x11\n\tlongitude\x18\x1a \x01(\x02\x12\x10\n\x08latitude\x18\x1b \x01(\x02\x12\x0f\n\x07\x63ountry\x18\x1c \x01(\t\x12\x10\n\x08location\x18\x1d \x01(\t\x12\x10\n\x08\x63ontract\x18\x1e \x01(\tb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MERCHANTCREATEREQUEST = _descriptor.Descriptor(
  name='MerchantCreateRequest',
  full_name='MerchantCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='MerchantCreateRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='MerchantCreateRequest.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='MerchantCreateRequest.material', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=113,
)


_MERCHANTCREATERESPONSE = _descriptor.Descriptor(
  name='MerchantCreateResponse',
  full_name='MerchantCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='material_identity', full_name='MerchantCreateResponse.material_identity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=166,
)


_MERCHANTRETRIEVEREQUEST = _descriptor.Descriptor(
  name='MerchantRetrieveRequest',
  full_name='MerchantRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantRetrieveRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='MerchantRetrieveRequest.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identities', full_name='MerchantRetrieveRequest.merchant_identities', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=256,
)


_MERCHANTRETRIEVERESPONSE = _descriptor.Descriptor(
  name='MerchantRetrieveResponse',
  full_name='MerchantRetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='materials', full_name='MerchantRetrieveResponse.materials', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=322,
)


_MERCHANTBATCHRETRIEVEREQUEST = _descriptor.Descriptor(
  name='MerchantBatchRetrieveRequest',
  full_name='MerchantBatchRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='MerchantBatchRetrieveRequest.numbers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identities', full_name='MerchantBatchRetrieveRequest.identities', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=391,
)


_MERCHANTBATCHRETRIEVERESPONSE = _descriptor.Descriptor(
  name='MerchantBatchRetrieveResponse',
  full_name='MerchantBatchRetrieveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='materials', full_name='MerchantBatchRetrieveResponse.materials', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=462,
)


_MERCHANTUPDATEREQUEST = _descriptor.Descriptor(
  name='MerchantUpdateRequest',
  full_name='MerchantUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantUpdateRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='MerchantUpdateRequest.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity', full_name='MerchantUpdateRequest.merchant_identity', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='material', full_name='MerchantUpdateRequest.material', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=585,
)


_MERCHANTUPDATERESPONSE = _descriptor.Descriptor(
  name='MerchantUpdateResponse',
  full_name='MerchantUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=611,
)


_MERCHANTDELETEREQUEST = _descriptor.Descriptor(
  name='MerchantDeleteRequest',
  full_name='MerchantDeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='MerchantDeleteRequest.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identity', full_name='MerchantDeleteRequest.identity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merchant_identity', full_name='MerchantDeleteRequest.merchant_identity', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=697,
)


_MERCHANTDELETERESPONSE = _descriptor.Descriptor(
  name='MerchantDeleteResponse',
  full_name='MerchantDeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=699,
  serialized_end=723,
)


_MERCHANTMATERIAL = _descriptor.Descriptor(
  name='MerchantMaterial',
  full_name='MerchantMaterial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MerchantMaterial.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_en', full_name='MerchantMaterial.name_en', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numbers', full_name='MerchantMaterial.numbers', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='verified', full_name='MerchantMaterial.verified', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qrcode', full_name='MerchantMaterial.qrcode', index=4,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contact_numbers', full_name='MerchantMaterial.contact_numbers', index=5,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='logo', full_name='MerchantMaterial.logo', index=6,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='MerchantMaterial.email', index=7,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='introduce', full_name='MerchantMaterial.introduce', index=8,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='MerchantMaterial.longitude', index=9,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='MerchantMaterial.latitude', index=10,
      number=27, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='MerchantMaterial.country', index=11,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='MerchantMaterial.location', index=12,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='contract', full_name='MerchantMaterial.contract', index=13,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=726,
  serialized_end=989,
)

_MERCHANTCREATEREQUEST.fields_by_name['material'].message_type = _MERCHANTMATERIAL
_MERCHANTRETRIEVERESPONSE.fields_by_name['materials'].message_type = _MERCHANTMATERIAL
_MERCHANTBATCHRETRIEVERESPONSE.fields_by_name['materials'].message_type = _MERCHANTMATERIAL
_MERCHANTUPDATEREQUEST.fields_by_name['material'].message_type = _MERCHANTMATERIAL
DESCRIPTOR.message_types_by_name['MerchantCreateRequest'] = _MERCHANTCREATEREQUEST
DESCRIPTOR.message_types_by_name['MerchantCreateResponse'] = _MERCHANTCREATERESPONSE
DESCRIPTOR.message_types_by_name['MerchantRetrieveRequest'] = _MERCHANTRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['MerchantRetrieveResponse'] = _MERCHANTRETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['MerchantBatchRetrieveRequest'] = _MERCHANTBATCHRETRIEVEREQUEST
DESCRIPTOR.message_types_by_name['MerchantBatchRetrieveResponse'] = _MERCHANTBATCHRETRIEVERESPONSE
DESCRIPTOR.message_types_by_name['MerchantUpdateRequest'] = _MERCHANTUPDATEREQUEST
DESCRIPTOR.message_types_by_name['MerchantUpdateResponse'] = _MERCHANTUPDATERESPONSE
DESCRIPTOR.message_types_by_name['MerchantDeleteRequest'] = _MERCHANTDELETEREQUEST
DESCRIPTOR.message_types_by_name['MerchantDeleteResponse'] = _MERCHANTDELETERESPONSE
DESCRIPTOR.message_types_by_name['MerchantMaterial'] = _MERCHANTMATERIAL

MerchantCreateRequest = _reflection.GeneratedProtocolMessageType('MerchantCreateRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTCREATEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantCreateRequest)
  ))
_sym_db.RegisterMessage(MerchantCreateRequest)

MerchantCreateResponse = _reflection.GeneratedProtocolMessageType('MerchantCreateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTCREATERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantCreateResponse)
  ))
_sym_db.RegisterMessage(MerchantCreateResponse)

MerchantRetrieveRequest = _reflection.GeneratedProtocolMessageType('MerchantRetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTRETRIEVEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantRetrieveRequest)
  ))
_sym_db.RegisterMessage(MerchantRetrieveRequest)

MerchantRetrieveResponse = _reflection.GeneratedProtocolMessageType('MerchantRetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTRETRIEVERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantRetrieveResponse)
  ))
_sym_db.RegisterMessage(MerchantRetrieveResponse)

MerchantBatchRetrieveRequest = _reflection.GeneratedProtocolMessageType('MerchantBatchRetrieveRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTBATCHRETRIEVEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantBatchRetrieveRequest)
  ))
_sym_db.RegisterMessage(MerchantBatchRetrieveRequest)

MerchantBatchRetrieveResponse = _reflection.GeneratedProtocolMessageType('MerchantBatchRetrieveResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTBATCHRETRIEVERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantBatchRetrieveResponse)
  ))
_sym_db.RegisterMessage(MerchantBatchRetrieveResponse)

MerchantUpdateRequest = _reflection.GeneratedProtocolMessageType('MerchantUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTUPDATEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantUpdateRequest)
  ))
_sym_db.RegisterMessage(MerchantUpdateRequest)

MerchantUpdateResponse = _reflection.GeneratedProtocolMessageType('MerchantUpdateResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTUPDATERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantUpdateResponse)
  ))
_sym_db.RegisterMessage(MerchantUpdateResponse)

MerchantDeleteRequest = _reflection.GeneratedProtocolMessageType('MerchantDeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTDELETEREQUEST,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantDeleteRequest)
  ))
_sym_db.RegisterMessage(MerchantDeleteRequest)

MerchantDeleteResponse = _reflection.GeneratedProtocolMessageType('MerchantDeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTDELETERESPONSE,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantDeleteResponse)
  ))
_sym_db.RegisterMessage(MerchantDeleteResponse)

MerchantMaterial = _reflection.GeneratedProtocolMessageType('MerchantMaterial', (_message.Message,), dict(
  DESCRIPTOR = _MERCHANTMATERIAL,
  __module__ = 'merchant_pb2'
  # @@protoc_insertion_point(class_scope:MerchantMaterial)
  ))
_sym_db.RegisterMessage(MerchantMaterial)


# @@protoc_insertion_point(module_scope)
