# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vip.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vip.proto',
  package='',
  syntax='proto3',
  serialized_pb=b'\n\tvip.proto\"\x0c\n\nVipRequest\"\r\n\x0bVipResponseb\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VIPREQUEST = _descriptor.Descriptor(
  name='VipRequest',
  full_name='VipRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=25,
)


_VIPRESPONSE = _descriptor.Descriptor(
  name='VipResponse',
  full_name='VipResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['VipRequest'] = _VIPREQUEST
DESCRIPTOR.message_types_by_name['VipResponse'] = _VIPRESPONSE

VipRequest = _reflection.GeneratedProtocolMessageType('VipRequest', (_message.Message,), dict(
  DESCRIPTOR = _VIPREQUEST,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:VipRequest)
  ))
_sym_db.RegisterMessage(VipRequest)

VipResponse = _reflection.GeneratedProtocolMessageType('VipResponse', (_message.Message,), dict(
  DESCRIPTOR = _VIPRESPONSE,
  __module__ = 'vip_pb2'
  # @@protoc_insertion_point(class_scope:VipResponse)
  ))
_sym_db.RegisterMessage(VipResponse)


# @@protoc_insertion_point(module_scope)
